#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "nord"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    autocomplete_method = "coc"
    disabled_plugins = ["clang_complete","delimitMate","l/vim-cpp-enhanced-highlight"]
    bootstrap_after = "autoneoformat#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "lsp"

[[layers]]
  name = "checkers"
  enable = false

[[layers]]
  name = "ui"

[[layers]]
  name = "git"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = false

[[layers]]
  name = "lang#extra"

[[layers]]
  name = "core#statusline"
  enable = false

[[layers]]
  name = "fzf"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#extra"

[[layers]]
  name = "lang#rust"
  format-autosave = 1

[[custom_plugins]]
  name = "dracula/vim"
  merged = 0

[[custom_plugins]]
  name = "liuchengxu/vista.vim"
  merged = 0

[[custom_plugins]]
  name = "jiangmiao/auto-pairs"
  merged = 0

[[custom_plugins]]
  name = "jackguo380/vim-lsp-cxx-highlight"


[[custom_plugins]]
  name = "vimwiki/vimwiki"
