format = """
[┌───────────────────────────>](bold green) $jobs$status$time$battery$memory_usage
[│](bold green)$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$cmd_duration\
$custom\
$lua
[└───>](bold green) $character"""

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[⁖](bold green)"     # The "success_symbol" segment is being set to "" with the color "bold green"
error_symbol = "[⁖](bold red)"     # The "success_symbol" segment is being set to "" with the color "bold green"

[status]
disabled = false

[time]
disabled = false

[memory_usage]
disabled = false
threshold = 30

[battery]
format = "[$symbol$percentage]($style) "

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold purple"

[[battery.display]]
threshold = 100
style = "bold green"
