#! /bin/sh

sxhkd &

bspc monitor -d terminal code browser comms misc VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a firefox desktop='^3'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a URxvt:urxvt_keys_help state=floating

$HOME/.config/polybar/launch.sh
feh --bg-scale ~/.config/wallpaper/nord-arch-16k.png &
picom --config ~/.config/picom/picom.conf
